apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-engine-sa
  namespace: chaos-engine
  annotations:
    # SECRET_REF: Replace with the chaos-engine IRSA role ARN from Terraform output
    eks.amazonaws.com/role-arn: "REPLACE_WITH_CHAOS_ENGINE_ROLE_ARN"
  labels:
    app: chaos-engine
