apiVersion: v1
kind: Service
metadata:
  name: chaos-engine
  namespace: chaos-engine
  labels:
    app: chaos-engine
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: chaos-engine
  ports:
    - name: http
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP
