apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: monitoring
  labels:
    app: tempo
    app.kubernetes.io/part-of: chaos-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
