apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependency-track-data
  namespace: security
  labels:
    app: dependency-track
    app.kubernetes.io/part-of: chaos-platform
spec:
  accessModes:    [ReadWriteOnce]
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi   # SBOMs and vulnerability DB can be several GB
